- name: ansible-test-playbook0
  hosts: localhost

  tasks:
  - name: print credential
    ansible.builtin.debug:
      msg: "Credential ID: {{ credential_id }} | Username: {{ credential_username }} | Password: {{ credential_password }}"
